name: Develop CI Build

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: windows-latest
        name: Develop CI Build
        steps:
            - name: Checkout repository
              uses: actions/checkout@master

            - name: Restore Packages
              run: dotnet restore -s https://api.nuget.org/v3/index.json

            - name: Build solution
              run: dotnet build -c Release

            - name: Run unit tests
              run: dotnet test -c Release
