name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400
   
    - name: Setup .NET 6 Preview
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.7.21379.14
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Talista.Conveyor/Talista.Conveyor.csproj
        TAG_COMMIT: true
        TAG_FORMAT: v*
        NUGET_KEY: ${{secrets.GITHUB_TOKEN}}
        NUGET_SOURCE: https://nuget.pkg.github.com/talista/index.json
        INCLUDE_SYMBOLS: true      
