name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --configuration Release
    - name: Packing nuget package
      run: dotnet pack --configuration Release
    - name: Register Package Source
      run: nuget sources Add -Name "github" -Source ${{ secrets.git_nuget }} -UserName ${{secrets.git_user }} -Password ${{ secrets.git_token }}
    - name: Publishing nuget package
      run: dotnet nuget push "bin/Release/talista.conveyor.1.0.0.nupkg" --source "github"
