name: NuGet Generation

on:
    push:
        branches:
            - '*'
            - '!main'

jobs:
    build:
        runs-on: windows-latest
        name: Update NuGet
        steps:
            - name: Checkout repository
              uses: actions/checkout@main

            - name: Restore Packages
              run: dotnet restore -s https://api.nuget.org/v3/index.json

            - name: Build solution
              run: dotnet build -c Release

            - name: Run Tests
              run: dotnet test
              
